---
- name: resolving vars for {{ prometheus_installer_app.name }} v{{ prometheus_installer_app.version }}
  include_vars:
    file: install-vars.yml

- name: checking for installation of {{ prometheus_installer_app.name }} v{{ prometheus_installer_app.version }} in  {{ prometheus_installer_dir }}
  become: true
  become_user: root
  stat:
    path: '{{ prometheus_installer_dir }}'
  changed_when: false
  register: prometheus_installer_binary

- when: not prometheus_installer_binary.stat.exists
  block:
    - name: downloading {{ prometheus_installer_app.name }} v{{ prometheus_installer_app.version }} from {{ prometheus_installer_tgz_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ prometheus_installer_tgz_url }}'
        dest: '{{ prometheus_installer_tmp_tgz }}'
        checksum: '{{ prometheus_installer_checksum }}'
        mode: 0644

    - name: unarchiving {{ prometheus_installer_app.name }} v{{ prometheus_installer_app.version }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ prometheus_installer_tmp_tgz }}'
        dest: '{{ prometheus_installer_parent_dir }}'
        creates: '{{ prometheus_installer_dir }}'
  always:
    - name: rm {{ prometheus_installer_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ prometheus_installer_tmp_tgz }}'
        state: absent

- name: linking subdirectories of {{ prometheus_installer_parent_dir }} to {{ prometheus_installer_dir }}
  become: true
  become_user: root
  with_items: '{{ prometheus_installer_link_dirs }}'
  file:
    src: '{{ prometheus_installer_dir }}'
    dest: '{{ item }}'
    state: link

- name: linking {{ prometheus_installer_link_exe }} to {{ prometheus_installer_fq_exe }}...
  become: true
  become_user: root
  file:
    src: '{{ prometheus_installer_fq_exe }}'
    dest: '{{ prometheus_installer_link_exe }}'
    state: link

- name: adding {{ prometheus_installer_app.name }} v{{ prometheus_installer_app.version }} to default path...
  become: true
  become_user: root
  template:
    src: shell.j2
    dest: /etc/profile.d/{{ prometheus_installer_app.name }}.sh
    mode: 0644
