---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: looping over programs to install...
  loop: '{{ prometheus_installer_versions }}'
  loop_control:
    loop_var: prometheus_installer_app
  include_tasks: install-program.yml
