---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Looping over programs to install...
  loop: '{{ prometheus_installer_versions }}'
  loop_control:
    loop_var: prometheus_installer_app
  ansible.builtin.include_tasks: install-program.yml
